### ISSUE TITLE
Passing in animation to $modalService

### ISSUE THREAD

**Issue by mjhamm75** [mgcrea/angular-strap#1101]
When I create a `modal` in my markup, the animation works like expected.  Here is an example:
`<a href="" bs-modal="settings.deleteAccountModal" data-animation="am-fade-and-slide-top" data-template="js/donor/settings/confirm-modal.html" class="trashOut"></a>`
But when I try to create the same modal with the `$modalService`, the animation does not work.  Here is my `js` code:

``` javascript
this.openModal = function() {
        $modal({
            animation: 'am-fade-and-slide-top',
            backdropAnimation: 'am-fade',
            scope: $scope,
            title: "Are you sure?",
            backdrop: 'static',
            template: 'js/donor/settings/confirm-modal.html',
            show: true
        });
    };
```

How do I configure the animations with the `$modalService`?

**Comment by Onlydreams** [comment]
Meeting the same question and here is my plunker:
http://plnkr.co/edit/DW4xTU9nTegyV1s9Tq6O 
The animation doesn't work.

**Comment by vmlf01** [comment]
You need to include both ngAnimate and custom CSS for the animations to work. AngularStrap uses AngularMotion CSS animations, but you can create your own.
Here is an updated plunker with the animations working: http://plnkr.co/edit/uK4QxyWnlvBWzsZ7MnPW?p=preview

I changed the script to load Angular 1.3 because there seems to be some compatibility issues with 1.4 as mentioned in another issue here.
