### ISSUE TITLE
Text in modal looks blurry

### ISSUE THREAD

**Issue by akaRem** [mgcrea/angular-strap#1234]
Mac 10.9.5, safari 7.1 (9537.85.10.17.1)
![2014-11-06 0 02 04](https://cloud.githubusercontent.com/assets/1472728/4925921/1264c08a-652f-11e4-9328-803a0f897675.png)

**Comment by dankahle** [comment]
I'm working on my own modal widget right now, and everything started getting fuzzy all a sudden. I had converted the translateX/Y's to translate3d, put them back and all is looking better. Still some weird text fuzzy to sharp going on, but probably was there all along. The fuzzy all the time thing was messing with me. Seems to have the most trouble with just one of my dialogs that's dynamically loaded from html. Thought I was losing it for awhile. Ended up rebooting my mac as a last resort. I guess it's a webkit thing. Prefixer's kicking out the -webkit prefixes, but there's something weird going on with that translate3d. Might be jank-free, but the blurry text is too much. Added the 3d lines back in to verify and guess what? Didn't come back. Took them out anyway. It didnt' go away until I got rid of the 3d's. I'm pretty sure that's where the whole mess started.

**Comment by dankahle** [comment]
This is my widget remember. So, I got rid of the full-time fuzzy text, but still had this fuzzy to sharp text that happened in the last 100ms of my 200ms animation in from opacity 0 to 1. I was doing centering with left/top 50% and translate(-50%, -50%). Ditched the translate and text and all comes in sharp as hell. Turn the animation time to 0s and the translate comes in sharp as hell. So for me it's a combo of my opacity animation mixed with the translate(-50%, -50%). It's livable but not liking it. Guess it will get fixed in the future. Funny thing is when everything went all blurry, wasn't my modal that was using the translate3d. I had stuff jumping into the page at page init that used the translate3d. I believe that's where the permanent fuzz came from, but oddly enough I wasn't using translate3d on the modal, I was just using the one above.

**Comment by dankahle** [comment]
In sheer desperation, I googled "fuzzy modal text", that's how I landed up in these comments :) . How funny.The comments got me pointed in the right direction though, so thanks for that guys.

**Comment by dankahle** [comment]
I'm working on my own modal widget and seeing this same problem. On my mac mini all a sudden noticed my modal was coming up blurry on chrome. Got frustrated, googled and landed here. Got the idea above it could be my translate3d I was using "on other divs" not even the modal. Changed the to translateX/Y or translate(x,y) and problem cleared up, but when I put 3d back on, didn't come back. What? I'm animating opacity (not translate), BUT I have translate (-50%,-50%) on my modal for centering. That's the culprit. Not happening on bootstrap, but bootstrap animates to translate(0,0). It's not and issue if translate(0,0) has to be translate(x,y) to have an issue. So what I have on mac mini without translate3d on these other divs is: jumpy text at end of opacity animation on chrome, same deal on firefox and permanent blurry text on safari. On windows I have jump text on chrome and that's all. Read that filter:blur(0) will fix it, and it's true that -webkit-filter:blur(0) fixes it on chrome, but filter:blur(0) will make firefox blurry. Neither fixes the permanent blur on mac safari though. If I had to use translate then I'd use -webkit-filter:blur(0), and suck it up for the mac safari fuzz text. As fate would have it though, I position all different ways with my modal, and already had width and height in my js so just centered it in js instead. How do I have height? I spin a cycle in js using $timeout to let the digest happen, then call jquery.outerHeight/Width() to get the dimensions. This makes my modal async, but allows me to position it anywhere as now I have the content-dependent height. 
$timeout(function () {
      defSpin.resolve(initObj);
}
my show() method calls init which returns a promise, it loads/compiles the template, then spins a cycle before resolving the promise for show(). This gives me dimensions based on content instead of handlebars.

**Comment by rwkyyy** [comment]
In my case none was working properly (chrome and safari on OS X 10.11.2).

I added a zoom:1.1!important for the id: #modal-login it made it a little bigger but now it's ok.

ps. I have font smoothing to antialiased as well.

**Comment by patribezek** [comment]
in my case the whole modal look blurry, i tried erasing the -webkit-blabla.. but chrome keeps it. if i add a -webkit-transform: none, my modal flyes away.. maybe it's for another issue but how can i block the inherited webkits?

**Comment by dankahle** [comment]
I haven't dealt with this project in forever, and there were other comments
that said this wasn't broken. The solution to this whole transform
translate thing is: flexbox, it will put things in the middle easily
without a transform, just a simple display:flex on the container and
margin: auto on the child. Flexbox is supported pretty well know and with
autoprefixer, back to IE10 or so.

**Comment by simoazzo** [comment]
Have someone find a solution?

**Comment by patribezek** [comment]
@simoazzo The best solution by the moment is the one mentioned by @dankahle, the problem is, if you have a translate property (something like -webkit-transform:translateY(2px);) the text will be burry, if you remove this and position your modal in other way the blurry will disapppear. th antialiased property seems not working (at least for me). hope it helps!

**Comment by dankahle** [comment]
I'm way out of the loop on this one, but these days flex is an valid option. Flexbox would do this easily with a simple: margin auto auto; inside a flexbox. Flex works all the way back to ie10 with prefixes (autoprefixer would kick out the prefixes).

**Comment by MiguelQueiroz** [comment]
I will be your friend ... what you need to do is after the animation trigger a normalizing function.

http://stackoverflow.com/a/42256897/1834212

**Comment by uxmaster** [comment]
I created a pull request to fix this: https://github.com/mgcrea/bootstrap-additions/pull/23

**Comment by mkdizajn** [comment]
After long searching online,, I've fixed my fckedup modal blur font with this fucker:

```
#modalID .modal-dialog{
	position: absolute !important;
}
```

hate that kind of style forcing from upstream guys :(

**Comment by yonghunjeong** [comment]
Thank you @mkdizajn Finally, your solutions works for me!!

**Comment by sachintha88** [comment]
I hope this is about centering the object into exact center of the screen.
Blurring happens with the 

`transform: translate(-50%,-50%);`

so instead doing 

```
position: absolute;
margin:0;
top: 50%;
left: 50%;
transform: translate(-50%,-50%);
```

I tried injecting style in to element using javascript. (React.js)


```
const node = ReactDOM.findDOMNode(this);
var width = node.offsetWidth;
var height = node.offsetHeight;
var windowWidth = window.innerWidth;
var windowHeight = window.innerHeight;

style={
    left : (windowWidth/2) - (this.state.width/2) + 'px',
    right:  (windowWidth/2) - (this.state.width/2) + 'px',
    top: (windowHeight/2) - (this.state.height/2) + 'px',
    bottom: (windowHeight/2) - (this.state.height/2) + 'px'
}

```
inject style into element by javascript style

Eg.

```
export default class Dialog extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            width: '0px',
            height: '0px'
        };
    }

    setWidthhandHeight(node){
        if (this.state.width !== node.offsetWidth) {
            this.setState({
                width: node.offsetWidth,
                height: node.offsetHeight
            });
        }
    }

    componentDidMount() {
        this.setWidthhandHeight(node);
    }

    render() {
        const windowWidth = window.innerWidth;
        const windowHeight = window.innerHeight;
        return (
            <dialog className={this.props.className + " dialog"}
                    style={{
                        left : (windowWidth/2) - (this.state.width/2) + 'px',
                        right:  (windowWidth/2) - (this.state.width/2) + 'px',
                        top: (windowHeight/2) - (this.state.height/2) + 'px',
                        bottom: (windowHeight/2) - (this.state.height/2) + 'px'
                    }}>
                {this.props.title ? (
                    <header><span>{this.props.title}</span></header>
                    )
                    : null
                }
                {this.props.children}
            </dialog>
        );
    }
}

```
