### ISSUE TITLE
Mimic the new behavior of modal backdrop (Bootstrap v3.3.0 update)

### ISSUE THREAD

**Issue by mfc-julius** [mgcrea/angular-strap#1263]
Following https://github.com/twbs/bootstrap/issues/15066#issuecomment-62403892 backdrop of modals are not visible due to the change and removal of z-index in original Bootstrap library.

**Comment by mgcrea** [comment]
```
.modal-backdrop {
  z-index: 1040;
  bottom: 0px;
}
```

This ended up working on the docs.

Tried to tackle this today. But animating nested elements with ngAnimate is a pain. The issue is that the parent element (`.modal`) must also have an animation for child animations to trigger. So it does not seem really viable.

A workaround would be to manually add `.modal` container to the DOM, then animate both the `.modal-backdrop` and `.modal-dialog` into it. Main issue is that it's a breaking change (container block is no more handled by the template). That's what @guzart did.

@guzart Any comment regarding this second implementation? Did it ended working well for you? What did hold you from submitting a PR?

**Comment by guzart** [comment]
@mgcrea the solution I was working on didn't work well and it seemed very artisanal and fragile, which is why I didn't submit a PR. I couldn't think of a clean non-breaking change for the animation.

**Comment by solarisfire** [comment]
.modal-backdrop {
      z-index: 1040;
      bottom: 0px;
    }

This only works until you scroll down a long page and trigger a modal at the bottom. The backdrop gets left at the top.
