### ISSUE TITLE
Datepicker autoclose="true" dosn't change bs-show to false

### ISSUE THREAD

**Issue by tamtakoe** [mgcrea/angular-strap#1351]
http://plnkr.co/edit/XUP3zP5MF2xBZGwet9fX?p=preview

**Comment by c-johnson** [comment]
I was going to write a lengthy comment about this, and I'd be happy to contribute a PR to help make this work.  

Essentially, it's very hard right now to use trigger='manual' with autoclose, since trigger='manual' requires the bs-show property to dictate the visibility of the datepicker.  As is, the best way (as shown in tamtakoe's example) is to just toggle a property that handles the visibility, but autoclose does not toggle this property and there's no way to hook into that.  The end result is that, once the user selects a date, they must click twice to re-open the datepicker (which happens a lot in our user testing).

Another angle would be to change "bs-show" attribute to accept a property instead of an expression, which then gives autoclose the ability to toggle that already-registered property.  

Again, I'd be happy to help contribute here.  I've never contributed to open source before, so this might be a good little improvement to get started with some guidance :)

**Comment by c-johnson** [comment]
Any approval of this from the maintainers?  I'd like to get started, just want to make sure I'm not wasting my time.

**Comment by vmlf01** [comment]
I think the bs-show value should be synchronized with the current visibility status, but let's see what @mgcrea has to say.

**Comment by c-johnson** [comment]
Ping.  Again, I'm 100% ready and willing to become an active contributor in this project, so... the moment we can move on this the moment I can get to work.

**Comment by c-johnson** [comment]
@vmlf01, should I give up on this?  I would really like to start contributing to open source, and particularly this project, but I don't know if there's a better way to start other than pinging you once every two weeks about this issue I have.

**Comment by vmlf01** [comment]
I think the best approach is just do it. The worse that can happen is that it doesn't get merged, but at least there is something that can be checked and tested :)

**Comment by c-johnson** [comment]
I suppose that's the common wisdom, I would just hate spending hours on something to find out it wasn't even a desirable feature in the first place.  Such is open source?

**Comment by mgcrea** [comment]
@c-johnson, sorry for the late response, I think synchronizing the `bs-show` value is the way to go. But it should be fixed across the whole framework (both `tooltip` & `modal`). 

Generally, if you provide a relevant use-case, a patch that respect both formatting and commit message guidelines along with according unit-tests. You can be pretty sure that your work will be merged into the master.

I did not have much time lately, but I'm carefully reviewing every PR out there (while ignoring most issues) to make sure the project continues to live. I'm open to add new contributors, but you must prove to be willing to put substantial work into the project (so more that a couple PRs first) and that we share the same vision for the project.

Thanks for your patience! I'm looking forward to checkout your code.
