### ISSUE TITLE
Collapse Animation

### ISSUE THREAD

**Issue by CarlosCuevas** [mgcrea/angular-strap#1390]
The default animation doesn't work unless you include http://mgcrea.github.io/angular-strap/styles/main.min.css

**Comment by psi-4ward** [comment]
my `slide-up-down-ani` class for ng-repeat and collapse

```javascript
app.animation('.slide-up-down-ani', function() {
  function enter(element, done) {
    jQuery(element).css({
      display: 'none'
    }).slideDown(200, done);
  }

  function leave(element, done) {
    jQuery(element).css({
      display: 'block',
      visibility: 'visible'
    }).slideUp(200, done);
  }

  return {
    enter: enter,
    leave: leave,
    addClass: function(el, className, done) {
      if(className !== 'in') return;
      enter(el, done);
    },
    removeClass: function(el, className, done) {
      if(className !== 'in') return;
      leave(el, done);
    }
  };
});
```

**Comment by sfarfarini** [comment]
The documentation misses the `@keyframe` part, because `animation-name` refers to `expand` and `collapse`, which are simple not in place in any standard css.
I extracted them by myself:

```
@keyframes expand {
  from { max-height: 0; }
  to { max-height: 500px; }
}

@keyframes collapse {
  from { max-height: 500px; }
  to { max-height: 0; }
}
```

This is confusing, because not specifying the animation in the custom css seems they are taken from some standard-css that should be included, like from angular-motion or bootstrap, but it-s not.
Please add them to the docs or change the animation to something which does not require custom css.

**Comment by belfz** [comment]
What's the status of this bug? I still can't make the bs-collapse animations working. Any solutions?

**Comment by vmlf01** [comment]
Possible animation implementation, as mentioned above:
http://plnkr.co/edit/fV1RXB5zsCHnuwBR8N9b?p=preview

**Comment by belfz** [comment]
Thank you, that works fine.
