### ISSUE TITLE
bsAffix Issue After changing routes with ngRoute

### ISSUE THREAD

**Issue by jsteinshouer** [mgcrea/angular-strap#1493]
On initial page load my affix element seems to pin to the correct position but after changing routes using ngRoute I have to scroll half way down the page before my element appears. Any ideas what I may be doing wrong. Here is the markup I am using.

```
 <div class="bs-sidebar" data-offset-top="-60" bs-affix>
```

**Comment by ELJK** [comment]
I am having the same issue. Help would be much appreciated.

**Comment by fvisser** [comment]
We encountered the same problem. The underlying problem is that the bsAffix directive is triggered before the DOM is rendered after a route change. Because of this the offsets are not calculated correctly. Just wrapping the postlink code in a timeout solves the problem. 

We will create a pull request with the fix

**Comment by ntvsx193** [comment]
Hm... I'm think, used `$timeout` bad idea.

**Comment by CyborgMaster** [comment]
`$timeout` is the only way I know of to delay execution until after the dom has rendered.  In this case it is vital, because there is no way to know the initial offset of the element until after the page has rendered.  I'm have to use this branch to get things to work with ngRoute.  I vote to have this merged.

**Comment by CyborgMaster** [comment]
I have fully tested this patch and found it to work great.  I would love to get it merged because this is a change to only the source file.  I can't use the fork directly because the compilation into `dist` hasn't been run on the fork (as it shouldn't be) and so the main js file hasn't been modified to reflect the patch.  For now, I've made my own fork and manually applied this little patch to the dist file directly.
