### ISSUE TITLE
Typeaheads doesn't work with objects

### ISSUE THREAD

**Issue by Carw** [mgcrea/angular-strap#1556]
There is an example with icons, where we can see objects like:
_{"value":"Gear","label":"<i class=\"fa fa-gear\"></i> Gear"}_

But we can't set value with _$scope.selectedIcon = ""_ manually;

Example with States
http://plnkr.co/edit/qSIqwkHBMftwijWTPzL8?p=preview

**Comment by stanleyxu2005** [comment]
I checked the source code. It looks wired to me..
```
          var selected = angular.isDefined(index) ? typeahead.$scope.$matches[index].label : controller.$viewValue;
          selected = angular.isObject(selected) ? parsedOptions.displayValue(selected) : selected;
          var value = selected ? selected.toString().replace(/<(?:.|\n)*?>/gm, '') : '';
          element.val(options.trimValue === false ? value : value.trim());
```

Let's use official example data 
```
$scope.icons = "[{"value":"Gear","label":"<i class=\"fa fa-gear\"></i> Gear"},{"value":"Globe","label":"<i class=\"fa fa-globe\"></i> Globe"},{"value":"Heart","label":"<i class=\"fa fa-heart\"></i> Heart"},{"value":"Camera","label":"<i class=\"fa fa-camera\"></i> Camera"}];
```
When `{"value":"Gear","label":"<i class=\"fa fa-gear\"></i> Gear"}` is matched, the variable `selected` become `"<i class=\"fa fa-gear\"></i> Gear"`. I am expecting it to be `{"value":"Gear","label":"<i class=\"fa fa-gear\"></i> Gear"}`. So the varialbe `value` will not equal to "Gear". 

In official example, it looks fine, because `selected.toString().replace(/<(?:.|\n)*?>/gm, '')`, which changes `"<i class=\"fa fa-gear\"></i> Gear"` to Gear.
