### ISSUE TITLE
bs-radio-group doesnt work when i include bootstrap js

### ISSUE THREAD

**Issue by Bana0615** [mgcrea/angular-strap#1642]
the bs-radio-group doesnt work when i include jquery into my product. Is there any way around this i love angular strap but bootstrap doesnt even work without jquery  plus i still use bootstrap.js for a few things.

**Comment by vmlf01** [comment]
The problem probably is not jquery, it should be because you are including bootstrap.js.

**Comment by Bana0615** [comment]
i know i changed it to bootstrap.js is there any way to still use bootstrap.js and angularstrap tho

**Comment by vmlf01** [comment]
Probably not, because both libraries will act upon the same html elements, which causes conflicts and unexpected behaviour.

**Comment by arteme** [comment]
Hi, I am the most recent casualty of this issue. While it is understandable that there is an overlap between the libraries here, it is by no means obvious that the two are incompatible. This is further complicated by the fact that it is not all directives that don't work, but only certain ones.

 I'd like to suggest that it be mentioned in the documentation in block letters (or otherwise so that it stands out) that to function correctly AngularStrap requires that bootstrap.js is excluded from the project.
