### ISSUE TITLE
Angular 1.3.15 V/s Angular Strap 2.2.1 Typeahead not showing droplist

### ISSUE THREAD

**Issue by sameer22** [mgcrea/angular-strap#1646]
As above, Can I use the versions as mentioned.

If yes, can you please check the Typeahead functionality that not showing the dropdown list.

Thanks.

**Comment by mantenpanther** [comment]
Doesn't work for me either, I get the following angular-error:
TypeError: Cannot read property '2' of null

I just tried the "States" example from the docs.

**Comment by vmlf01** [comment]
Here is a plunker generated from the docs pages with the minimum stuff:
http://plnkr.co/edit/kg3ykzArIvNxQ8MW9B0A?p=preview

I don't get errors on Firefox, can you please play with it and see if you still get errors?
What exact steps do you take that cause the error?

**Comment by sameer22** [comment]
Plunker is working fine at my end.

I compared the HTML and found, for droplist I used ng-options while plunker says bs-options. After changing, worked at my end also.

Any suggestions on it. Thanks.

**Comment by vmlf01** [comment]
That was a breaking change made in https://github.com/mgcrea/angular-strap/commit/6bb572e9342d9d893a8d2d37634e799e58dfc4a6.
When using AngularStrap version 2.2.0+, you should use bs-options instead of ng-options.

**Comment by sameer22** [comment]
Thanks.

**Comment by mantenpanther** [comment]
I found the issue - it had nothing to do with bs-options. The problem is on the docs-page, where the the CDN-Links are not correct (no protocol) and the scripts were not loaded. Maybe you want to correct the docs.

Here the current links:

<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular-strap/2.1.2/angular-strap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular-strap/2.1.2/angular-strap.tpl.min.js"></script>

**Comment by vmlf01** [comment]
Those are links to an older version of AngularStrap - 2.1.2 - which is before the bs-options breaking change.

Regarding the links, they should work - see here for more details on using protocol relative urls: http://blog.httpwatch.com/2010/02/10/using-protocol-relative-urls-to-switch-between-http-and-https/

**Comment by mantenpanther** [comment]
Ok, thanks for the info!
