### ISSUE TITLE
bs-options filtered array not updating

### ISSUE THREAD

**Issue by twjacobsen** [mgcrea/angular-strap#1744]
Hi,

When having a `| filter:something` on the source-array of `bs-options`, changes to the filter won't update the options in the dropdown.

I've made a modified version of the demo from docs:
http://plnkr.co/edit/h1Da8evi0Sqssz2WDXEP?p=preview

The "Regular filter" part uses the inline `| filter:` syntax, which does not work.

The "Function with filter" part uses the `$filter` service to return the filtered result

The above works just fine with the regular ngOptions, as shown in the last dropdown.

If relevant, this is implemented using Angular 1.4, but in the plunk, using angular 1.3, it does not work either.

**Comment by benbynum** [comment]
Any updates on this? I'm new to angular and having the same issue. I'm guessing because bs-options isn't actually bound to the data it only fires on load. Ideas:

1) Find a way to bind the data to bs-options so that any changes are immediately updated
2) Somehow "refresh" bs-options
3) Use vanilla JS to change the value of bs-options
4) ???
