### ISSUE TITLE
Typeahead doesn't work with async ajax calls with Angular 1.4.0.

### ISSUE THREAD

**Issue by gommo** [mgcrea/angular-strap#1780]
You can break the plunker demo by changing to angular 1.4.0 and the type ahead for async demo doesn't' work.

http://mgcrea.github.io/angular-strap/#/typeaheads-examples

**Comment by jswann** [comment]
+1 Just discovered this same issue and was looking to see if it had been reported yet.

If i revert back to 1.3.x of Angular typeahead works.

**Comment by jswann** [comment]
I've done some debugging and I was able to find the following:
The valuesFn function on $parseOptions is throwing the error 'Error: [filter:notarray] Expected array but received: {}' I had to add a debug statement in the catch to see this error.

**Comment by gommo** [comment]
Yeah I saw that. That was added specifically for that, but I'm wondering if it's hiding a bigger error?

**Comment by jswann** [comment]
I've been able to track it down to the adding of the filter on the bsOptions object. 
If i comment out the line: 
if (filter) bsOptions += ' | ' + filter + ':$viewValue';

Then everything works. Whenever the $parse is called on the match[7], the result is a promise not an array so the filter fails because it's not an array, undefined or null, per AngularJs's error reference (https://docs.angularjs.org/error/filter/notarray)

It would appear to me that the $parse should be called without the filter, then after the promise is resolved should the filter be applied. Possibly with $filter. I'm not familiar enough with the implementation of this code but i'll try to make a suggested patch and see if it's accepted.

**Comment by mgcrea** [comment]
Fixes by 2d3eb295ab23034e2f5838a2c68674d404d69028.
