### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by IdanCo** [mgcrea/angular-strap#1861]
Anyone gave angular-strap a spin with BS4?

I know it's built for BS3, and i know they've just released alpha now, but they claim to have good backward compatability, i was wondering how angular-strap is handling it...

**Comment by squadwuschel** [comment]
There is no claim About good Backwards Compatibility - see Panels in V3 and Cards in V4 complete renaming of components.

It would be cool if AngularStrap could Stay in Bootstrap 3 and Perhaps create a new Repository for Bootstrap 4 and Wait until AngularJS 2.0 is released, so that you could Create new AngularStrap with Bootstrap 4 and AngularJS 2.0 - two big changes :-/ and provide standard Support for the old version with Bootstrap 3 and AngularJS 1.x

**Comment by IdanCo** [comment]
You're right about backward compatability, i misinterpreted their docs.

There's also some logic to binding BS4 and Angular2 toghether, they have both dropped support for <IE9. but this can happen in 6 months or in two years, I wouldn't bind any project to such a rare celestial event.

**Comment by alalonde** [comment]
I think the Angular2 / BS4 combination would require an entirely new library -- too many breaking changes.

**Comment by mgcrea** [comment]
The discussion can continue in #2016!

**Comment by Zelgadis87** [comment]
Out of curiosity, why are Angular2 and BS4 so closely related?
Does the BS4 compatibility require such a massive rewriting investment, comparable to that of porting the existing code to Angular2?

I, for one, was considering creating a new app with BS4 and AngularJS, but I'm now not sure anymore that is a right call.
Thanks!

**Comment by mgcrea** [comment]
@Zelgadis87 I don't think there will be any major issues if we had to convert existing code to BS4, but it would be pretty hard to support both BS3 and BS4 with the same codebase. So it would require to provide "flavored" builds, and that's some more work.

With the Angular2 rewrite, we start with a clean state with the future in mind, so it does make sense to focus on Bootstrap4 from the scratch.

Ideally I'd love to be able to cross-compile Angular2Strap to AngularStrap. So that Angular1 user would benefit from the ongoing work. But it will probably be a bit hard to achieve.

**Comment by Zelgadis87** [comment]
I see, thanks for the answer!
