### ISSUE TITLE
$modal Resolve is not resolving the promise.

### ISSUE THREAD

**Issue by avarndell** [mgcrea/angular-strap#1868]
var myModal = $modal({templateUrl: config.templateUrl, scope: scope,  show: true, animation: "am-fade-and-scale", placement: "center", resolve: config.resolve});

Resolve is not resolving.

**Comment by vmlf01** [comment]
Can you post a sample test case please?

**Comment by harrzs** [comment]
I've come across the same issue, also with 'locals'. Maybe because the directive ignores the attributes 'resolve' and 'locals'?
`      angular.forEach([ 'template', 'templateUrl', 'controller', 'controllerAs', 'contentTemplate', 'placement', 'backdrop', 'keyboard', 'html', 'container', 'animation', 'backdropAnimation', 'id', 'prefixEvent', 'prefixClass', 'customClass', 'modalClass', 'size' ], function(key) {
        if (angular.isDefined(attr[key])) options[key] = attr[key];
      });
`
