### ISSUE TITLE
bs-typeahead: dropdown-menu has two time offset when key in for the first time

### ISSUE THREAD

**Issue by eddie11n** [mgcrea/angular-strap#1869]
After updated to angular 1.4.5

![c3942301-dd78-4cee-9bee-e9e73b03c17c](https://cloud.githubusercontent.com/assets/1493845/9896664/04754fae-5c72-11e5-8090-e75c99ad5c2f.png)

Problem maybe caused by return {0,0,0,0}  from element.getBoundingClientRect() in dimesions.js
![775aab98-4f99-438e-85ba-d69a14767417](https://cloud.githubusercontent.com/assets/1493845/9896692/7fa8fc7a-5c72-11e5-88ad-3635b089802a.png)

related to css of ng-hide
![46e4a152-fdb9-4935-b4b6-47b70ef8a7c8](https://cloud.githubusercontent.com/assets/1493845/9896712/bd193ac0-5c72-11e5-8823-5a3a77b8fb04.png)

I fixed it with css

> .ng-hide:not(.ng-hide-animate) {
>     display: block !important;
>     position: absolute;
>     top: -9999px;
>     left: -9999px;
>     &.dropdown-menu {
>         height: 0;
>         padding: 0;
>     }
> }

**Comment by raymond301** [comment]
I have this issue. Identical accept different versions.

* angular-strap  @version v2.3.10 - 2016-10-17
 * @license AngularJS v1.5.8

![screen shot 2017-01-10 at 9 29 27 pm](https://cloud.githubusercontent.com/assets/392344/21834653/6ed93df2-d77c-11e6-9eae-d6a28509a01c.png)

This CSS doesn't work, since .ng-hide is no longer used.
