### ISSUE TITLE
ui bootstrap pagination inside a modal not working

### ISSUE THREAD

**Issue by wfsiew** [mgcrea/angular-strap#1972]
You try to use a modal, the modal contains pagination from ui bootstrap, and whenever the page changed, the page ng-model variable always set to 1. I have tested with ngstrap version 2.3.6 and 2.3.5. But there is no such issue in version 2.2.4

**Comment by eaguirre1985** [comment]
Good morning.

I would like to know if this problem was solved. I am also working with angle 6 and within a modal place the pagination of ngx-pagination and it does not advance always stays on page 1. if there is any solution I thank you, so far I start with angular

**Comment by eaguirre1985** [comment]
I already solved the issue was to put ID to each pagination an id since the modal is shown in the same page that calls it. I leave the example and the pagiona of the documentation

<ul>
  <li * ngFor = "let item of collection | paginate: {itemsPerPage: 10, currentPage: p1, id: 'first'}"> ... </ li>
</ ul>
<pagination-controls (pageChange) = "p1 = $ event" id = "first"> </ pagination-controls>

<ul>
  <li * ngFor = "let item of collection | paginate: {itemsPerPage: 10, currentPage: p2, id: 'second'}"> ... </ li>
</ ul>
<pagination-controls (pageChange) = "p2 = $ event" id = "second"> </ pagination-controls>

http://michaelbromley.github.io/ngx-pagination/#/
