### ISSUE TITLE
Uncaught TypeError: el.focus is not a function

### ISSUE THREAD

**Issue by jimmyhernandez** [mgcrea/angular-strap#1977]
Hi I try to use the angular-strap library but I received this error.
Uncaught TypeError: el.focus is not a function

This is my code:

// Pre-fetch an external template populated with a custom scope
  var myOtherAside = $aside({
        title: "TCOR Menu",
        scope: $scope,
        templateUrl: "apex/tcor_menu_html",
        animation: 'am-fadeAndSlideLeft'
    });
  // Show when some event occurs (use $promise property to ensure the template has been loaded)
  myOtherAside.$promise.then(function() {
    myOtherAside.show();
  })

 I appreciated if you can give me some advise to use the library. I try it to the template:

Thanks.

**Comment by DaleWebb** [comment]
Could you attach your HTML template here?

**Comment by davison** [comment]
I just found that I was hitting this same issue (angular-strap 1.3.0) and it turned out to be because the first line in the template file I was loading was an HTML comment.  If you breakpoint line 2290 of angular-strap.js and when it hits the breakpoint, check the value of the el variable in the console.  In my case, it was the comment node and not the div which defined the modal dialog.

Removing the comment from the template fixed this for me.

**Comment by prabhumachismo** [comment]
Hi Team,

After using the below-listed js files causing multiple console issues likes(placeholder is undefined, focus() is not function) and so on and it's because of the **colspan** calling in the table, I have been trying to fix it for the last 2days, so kindly help me on this.

FYI...Chrome is working fine but still showing the console error, but when it has come to IE-Edge toggle effect showing issues just because of the **colspan** property

**Table category:** Swipe and Toggle
**Version:** *! Tablesaw - v3.1.1
**tablesaw.js**
**tablesaw-init.js**

![image](https://user-images.githubusercontent.com/3040144/55748442-528d6500-5a5c-11e9-85c7-c6a1d1328c20.png)
