### ISSUE TITLE
[Official] Angular2Strap discussion

### ISSUE THREAD

**Issue by mgcrea** [mgcrea/angular-strap#2016]
## Angular2 discussion and roadmap

Angular2 beta has landed a few weeks ago and it's now time to prepare the future of the project with an official plan for AngularStrap! This issue aims to centralize discussion around this next iteration of the project. I'd love to have both your input and help to review, discuss and actually shape Angular2Strap, I'm actively looking for new co-contributors to help move the project forward! 

 AngularStrap always aimed to be as simple and intuitive as possible, I'm really looking forward to achieve the same thing with Angular2.

Here are some questions that we should answer before moving on with actual code:

---
1. **Hosting:** Should the project live in a new GitHub project (angular2-strap), or be angular-strap v3? _Might be easier to start clean (at least for issues!)._
2. **Naming:** What name should this new project have? _Angular2Strap?_
3. **Tooling:** What starter-pack / tooling should we use? _I've seen a lot of different project/options. It looks like this [webpack-powered-one](https://github.com/AngularClass/angular2-webpack-starter) might be a promising one for now, I really liked my experience overall with webpack when playing with React._
4. **Retro-compatibility:** Should we try to write code that could work for angular1 too? _I'm not sure this is even possible, but if we use classes to embed most of the logic, there might be a way to have AngularStrap leverage them (maybe with a decorator override? Or an extra transform plugin from Babel). Would be awesome to have angular1 user benefit from the rewrite too, but it may be a bit far-fetched._
5. **Architecure:** Should we closely follow related projects architecture? _Like [angular2-material](https://github.com/angular/angular/tree/master/modules/angular2_material), etc._ 
6. **Bootstrap-version:** Should we start with [Bootstrap4](https://v4-alpha.getbootstrap.com/) still in alpha?
7. **Bootstrap-javascript:** Should aim to match Bootstrap own javascript implementation?

---

If you have other questions in mind, don't hesitate to send them my way, I'll update this post along the way.

Thanks!

PS: _Clearly, #2016 will be the year of Angular2 ;-)._

**Comment by squadwuschel** [comment]
Hi,
to 1) I think it would be better to start a clean new project from scratch, in TypeScript and Angular2.
to 2) your name would be great
to 4) I don't think you need to focus on compatibility on AngularJS 1.x because so far I've read some artikels about ngUpgrade and with this you could use angular 2 with angular 1 in the same project.
to 6) I don't use Bootstrap 4 atm but when you start a new project I think it would be cool if you would support Bootstrap 4.  I think it would be cool if you could provide two Versions of Angular2Strap with twi diffrent Templates which are compatible with Bootstrap 3 or 4. But I don't know if its possible.

in my opinion it would be cool if you would write Angular2Strap with TypeScript.

**Comment by angelxmoreno** [comment]
hey @mgcrea , Not sure if this is open to everyone that uses it or just contributors, but I'll open my big mouth and say a few things: 

1. Hosting: I agree with @squadwuschel that a new repo would be prefered

2. Naming: Angular2Strap makes it very clear what it is.

3. Tooling: No opinion. I'm one of those rare breeds waiting for more evidence before he decides.

4. Retro-compatibility: negative. lets keep it clean. I would hate to add any extra fat or complexity to achieve this.

5. Architecture: I like this but it only works if other projects follow. Keeps the community on the same page.

6. Bootstrap-version: How hard would it be to go from 3.x to 4.x once 4 goes beta? Thinking about the future, Angular2Strap ( I'm already using the name, lol ) would technically not be considered ready for production until both Bootstrap AND Angular2 are ready. I would lean towards Bootstrap 3 rather than leveraging two dependencies pre-RC

7. Bootstrap-javascript: This would be hard if we decided to start with 3 and move two 4. No opinion here.

**Comment by JumpLink** [comment]
1. Hosting: Yes, the project should live in a new GitHub project called angular2strap for a start clean start at least for issues.

2. Naming: I like Angular2Strap.

3. Tooling: I need to try this Webpack Starter Pack for a better opinion first, but makes a good impression.

4. Retro-compatibility: I think it is better to have AngularStrap V1 with Bootstrap 3 for Retro-compatibility and Angular2Strap is just for Angular 2 with Bootstrap 4. Both Angular 2 and Bootstrap 4 do not support old browser any more, right?

5. Architecure: Yes I think you should follow related projects architectures like [angular2-material](https://github.com/angular/material2), etc. because such projects will be the most widely used and the de facto standard, everything else will be found in the development process.
 
6. Bootstrap-version: V4, clean start at all, no contaminated sites, focus on the essentials.

7. Bootstrap-javascript: As far as I know Angular 2 works better with other javascript frameworks which manipulates/uses the DOM, but that would need jQuery, I think it is better to write you own implementation, which is again the cleaner way.

**Comment by DaleWebb** [comment]
1. **Hosting:** I also think that it should be hosted in a new repository.

2. **Naming:** Angular2Strap sounds fine (although it might sound like a conversion tool) what about keeping the hypen like Angular2-Strap.

4. **Retro-compatibility:** I think there would be too much overhead, constraints and restrictions by trying to support Angular 1 (similar to a framework trying to support an older version of IE).

6. **Bootstrap-version:** Would Bootstrap4 be production-ready before this is?  If so, I think we should aim for Bootstrap4 so that users can expect that this is going to be for Bootstrap4 and not 3 (then have to upgrade)

**Comment by bstruthers** [comment]
1.  **Hosting**: My vote is for a new project and a fresh start.
1. **Naming**: I like @DaleWebb's idea about keeping the hyphen: angular2-strap
1. **Tooling**: My only thought is to use TypeScript to keep things consistent.  
1. **Retro-compatibility**: I like the clean break.  If there's something we want to backport or share, we can figure it out as we go.  Just like A1 and A2.
1. **Architecture**: I like the idea of closely following related project's architecture.
1. **Bootstrap-version**: It's all about the timing.  If possible, Bootstrap4 is preferred.  I don't know how long Bootstrap4 will be in alpha.  Angular2 is closing in on a RC.
1. **Bootstrap-javascript**: One of the challenges we faced was with re-implementing Bootstrap's JS (popovers) was falling behind.  I'd prefer to not add a dependency on anything and keep the implementation with the project but think we need some sort of tracker/roadmap that we could use to keep tabs on how closely we're matching Bootstrap.

**Comment by squadwuschel** [comment]
My current biggest problem is, that I've a lot of projects written in Angular 1.x and Bootstrap 3.x. Its possible for me to use Angular 1.x and Angular 2.x in one app with ngUpgrade but thats not possible because most of the new Angular 2 frameworks for Bootstrap seem only to be written for Bootstrap 4. So it would be cool if Angular2-strap could provide a way to support Bootstrap 3 and 4 Templates with Angular 2 Code. 

It would be cool if you can keep this in mind and I am not the only developer having this kind of Migration Problems because of two changes at the same time.

**Comment by joschi127** [comment]
I also really like the name Angular2Strap. And I'm looking forward to see how this new project evolves. Having Angular Strap for Angular 2 available would be the right basis for us to start porting projects from Angular 1 to 2, because we are using the Angular Strap Components a lot.

I also think that Angular 1 support is not needed but it would be great to have some transition in mind, like allowing AngularStrap und Angular2Strap Code to coexist within the same project. 

Maybe a bit off-topic, but... When thinking about the transition to Angular 2: What do you all think about it? Are all of you planning to migrate to Angular 2? I've also had a closer look at Aurelia and played around with it a bit and it looks really really nice to me. However it seems like Angular 2 is still much more popular and so it maybe just ist the right and best way to go.

**Comment by richardm** [comment]
Did anything ever come of this?
