### ISSUE TITLE
Feature request: Select using native on mobile

### ISSUE THREAD

**Issue by chielsen** [mgcrea/angular-strap#2073]
I love NgStrap. But on mobile the select box is often not very user friendly. I would love having the option to fallback to native when selecting the dropdown.

**Comment by DaleWebb** [comment]
I imagine the dropdown would be quite small on mobile.

If this was a basic select or dropdown component, I would think it would be possible to activate the native mobile implementation of it - the problem is that because you can provide a custom template for the directive, the ngStrap dropdown could be more complicated than a native dropdown.

I would suggest either:

- Creating your own "thin" directive that will render either a native select component (stylise that however you want) if it is on mobile, and renders the `bs-select` component if you're on a non-mobile device.
- Create custom CSS and create your own template that has a responsive dropdown.

I hope that helps
