### ISSUE TITLE
Do not call $animate.leave(tipElement) in $tooltip.hide() in case if tipElement is null

### ISSUE THREAD

**Issue by akuznetsov-gridgain** [mgcrea/angular-strap#2090]
Hi!

Consider following use case:
I have a table with rows.
Each row contains label and [x] button.
[x] button has a tooltip (on hover) and on click row is deleted from table.
In debugger I see that tipElement is null when AngularStrap tries to hide tooltip, but as it was removed null is passed to $animate.leave() function and later results in NPE.

I think a check for null should be added in tooltip.js in $tooltip.hide = function (blur) {}

Thoughts?

**Comment by joshwhatk** [comment]
+1 I have a similar problem with the $modal.hide() method as well.

[plnkr example](http://plnkr.co/edit/ljytGHcKN1s7aKXNrWZg?p=preview)

**Comment by DaleWebb** [comment]
I couldn't reproduce from your plnkr, @joshwhatk

**Comment by akuznetsov-gridgain** [comment]
JFY same issue discussed in Angular Animate
https://github.com/angular/angular.js/issues/14211

Maybe you could take some useful info.

**Comment by joshwhatk** [comment]
I'm not sure entirely what you mean? If you're trying to recreate the problem again from my plnkr, or if you aren't seeing the error there. 

It throws the error to the console when clicking the "Save" button on the modal. 

The root cause seems to be described in the [Uncaught TypeError](https://github.com/angular/angular.js/issues/14211#issuecomment-211874523) Issue.

**Comment by DaleWebb** [comment]
Sorry, I meant I couldn't see the error there.  I clicked off the modal to hide it.  I can see it now that I click save.

I'll check out the Angular thread now.

**Comment by akuznetsov-gridgain** [comment]
If any one interested here a decorator that we are using while bug is not fixed:
```
angular.module('mgcrea.ngStrap.tooltip')
    .decorator('$tooltip', ['$delegate', ($delegate) => {
        function TooltipFactoryDecorated(element, config) {
            const delegate = $delegate(element, config);

            const scope = delegate.$scope;

            const options = delegate.$options;

            const hideWraped = delegate.hide;

            delegate.hide = (blur) => {
                if (!delegate.$isShown)
                    return;

                if (delegate.$element !== null)
                    return hideWraped(blur);

                scope.$emit(options.prefixEvent + '.hide.before', delegate);

                if (angular.isDefined(options.onBeforeHide) && angular.isFunction(options.onBeforeHide))
                    options.onBeforeHide(delegate);

                delegate.$isShown = scope.$isShown = false;
                scope.$$phase || (scope.$root && scope.$root.$$phase) || scope.$digest();
            };

            return delegate;
        }

        return TooltipFactoryDecorated;
    }]);

```

**Comment by joshwhatk** [comment]
I also should mention that the reason why I brought this up is because when the error occurs, it disables scrolling in Google Chrome (I'm not sure about other browsers), until refresh, which is a very big problem for an SPA.

I have updated the [plnkr](http://plnkr.co/edit/ljytGHcKN1s7aKXNrWZg?p=preview) so that now you can see that when Save is clicked the ability to scroll is removed. Once again, I have only tested this in the newest version of Google Chrome.

**Comment by DaleWebb** [comment]
I guess the `modal` related classes haven't been removed from the `<body>` yet.  Okay thanks

**Comment by DaleWebb** [comment]
@joshwhatk looks like you are destroying modal by overwriting the reference to it, on line 50.

I have re-written parts of the example here, so that it should work: http://plnkr.co/edit/tm9Mq1Ow5u71PPDPQJyw?p=preview

**Comment by joshwhatk** [comment]
So creating a new scope manually, and editing the parent scope there fixes the problem?

**Comment by DaleWebb** [comment]
Essentially not making your modal part of the object that you plan to overwrite.  So using the service via DI.

Or you could try this:
```javascript
vm.objects[vm.selected_index].msg = vm.selected_object.msg;
vm.objects[vm.selected_index].title = vm.selected_object.title;
```
rather than:
```javascript
vm.objects[vm.selected_index] = {
      msg: vm.selected_object.msg,
      title: vm.selected_object.title
    };
```

**Comment by joshwhatk** [comment]
Ok, that works for me. I can't simply overwrite each property of the object manually because I am using the post to the server to also pull in any possible updates to the object. However, making the modal not part of the scope that I overwrite so I can still do that makes a lot of sense.

Still think it shouldn't break the scrolling because $hide() is called after it's overwritten, but thank you very much for your help. I'll get to implementing that change.

**Comment by DaleWebb** [comment]
Yeah it shouldn't break the scrolling but what is breaking the scrolling is the classes that the modal appends to the body.  Those classes are removed later in the function of `$hide`.  As the modal doesn't expect to be destroyed whilst hiding, it throws an exception and cannot do the rest of the operations (e.g. removing the modal classes appended to the body)
