### ISSUE TITLE
Tooltip to remain open when hovering over it

### ISSUE THREAD

**Issue by LennyLip** [mgcrea/angular-strap#2120]
I was wondering whether it makes sense to support a feature like this: http://jsfiddle.net/WojtekKruszewski/Zf3m7/22/

Where you can hover over the tooltip and it still remains open, this way you enable the users to actually select text inside the tooltip or click links/buttons.

**Comment by DaleWebb** [comment]
So this is where you would hover over, then it opens forever until you close it in a different way (for example, clicking a button)?

**Comment by LennyLip** [comment]
@DaleWebb like in an in example. i want tooltip is open while mouse hover on an tooltip.

**Comment by DaleWebb** [comment]
Ah so while the mouse pointer is in the bounds of the tooltip, the tooltip should stay open?

**Comment by LennyLip** [comment]
@DaleWebb yes, how i can do this?

**Comment by DaleWebb** [comment]
I don't think there is a way to do this.  I was just trying to see if popovers and dropdowns have that ability (because if you hover over a dropdown, you expect someone to click an item in there) but they don't.

The reason why it doesn't work is because the element that triggered the tooltip to open via the mouse hover will close the tooltip when the mouse leaves the element.

You could use the `data-trigger="manual"` option, then get into the element and write your own logic for having the tooltip remain open and close.
