### ISSUE TITLE
Typeahead with async call double popup

### ISSUE THREAD

**Issue by avatarrosh** [mgcrea/angular-strap#2122]
When i select one entry from the list the selected value correctly displays in the typeahead, the popup disappears but shortly after a new popup comes out displaying only 1 entry, which is the one i already selected; I have to click it again to have a proper selection.
This happens **only with async calls**, and this issue also happens on the official angulastrap showcase page. Notice that the not-async calls are working properly.

**Comment by spencerwi** [comment]
This happens _constantly_ on a page where we have anywhere from 30 to 60 of these (it's a heavy data-entry screen with a product code lookup), and it creates all kinds of mistakes and slowdown for users.

Not only does the second popup appear when it shouldn't appear at all, but it also sometimes steals focus back after a delay, which means that you might type, choose an autocomplete option, have to immediately choose it again (repeat until you get frustrated and just click away), only to have focus jump _back_ into the previous input.

**Comment by spencerwi** [comment]
My hack-workaround so far has been convoluted ugly dom-querying logic bound to the `bs-on-select` event to _immediately_ jump to the next input as soon as you select an option.

**Comment by qqilihq** [comment]
Same issue here with current version 2.3.12 :(

**Comment by DaleWebb** [comment]
Could this be down to some form of race-condition? (just reading from the opening message in the issue)

**Comment by qqilihq** [comment]
Not sure, but my autocomplete function basically just returns the promise with the data. Nothing more is happening.

**Comment by DaleWebb** [comment]
Try using a timeout that would cancel results if another request is in-flight

**Comment by qqilihq** [comment]
Thank you for your suggestion, I would really like to try that, but I'm not sure whether I got the idea. Could you give a little more detail?

**Comment by DaleWebb** [comment]
Actually, I may have misunderstood the problem.  To try and make it less complicated, is the problem that your autocomplete function executes when it is already complete?

**Comment by qqilihq** [comment]
Basically, in my case, the issue is as follows. 

E.g. writing the word JavaScript into the typeahead:

1. User types into the field "ja"
2. Suggest function is called, async suggestion result arrives, suggestion results show up (at this point, no further method call is pending)
3. User selects "JavaScript" in the menu by clicking on the entry
4. The suggest function is called **again**, this time with the entry which was already "auto completed", i.e. "JavaScript"
5. Async suggestion result arrives, menu opens again and shows the single entry "JavaScript"

**Comment by DaleWebb** [comment]
Okay, I understand.

A naive, quick thought would be to not execute the search when an item is selected from the results.  That would be a function internal to the typeahead component, not something you and I would write.

Can you think of any problems with the above?

I might have a try when I have time, or you can go ahead and submit a PR.

**Comment by spencerwi** [comment]
I've moved jobs since I last commented and no longer use this framework in my day-to-day, but I tried a PR at the time, and didn't get very far. The angular-strap codebase is a very odd kind of "modular", where it's hard to actually tell where and how things are happening due to a custom "define"-style function that accepts some unspecified args.
