### ISSUE TITLE
Timepicker invalid-min-time when null

### ISSUE THREAD

**Issue by ChrisB92** [mgcrea/angular-strap#2140]
If I have 2 timepickers (From time and To time) and set To to have a min-time of From time, and then select a time in To, it all works as intended.

If I then remove the value from To (model is now null) and change From to be a time after was was previously set in To, it causes To to be invalid.

https://plnkr.co/edit/3oVNdDk2MRfNXqAMGQDV?p=preview

Steps:
1. Add value to To field that is x hours ahead of From
2. Remove value from To (so model is null)
3. Set From field to be x hours ahead of what the value of To was
4. Observe validation classes on To field

**Comment by DaleWebb** [comment]
I couldn't see a problem here. The to field is invalid because the value is null

**Comment by ChrisB92** [comment]
But it's only invalid when I change the From field to be ahead of what the To field was before it was null, otherwise it's valid (how I'd expect). Surely null should only be invalid when the field is required which To isn't?

**Comment by DaleWebb** [comment]
Ah I see what you mean, you didn't mention the required / not required part of this haha.

Yes, I think you're right.  I would expect that if it is required then it should check if it has a value and it is a value that is a date ahead of the minimum date and below maximum.  Otherwise if it isn't required, the check should only happen if there is a value.

Would you agree?

**Comment by ChrisB92** [comment]
Sorry, I probably should have included that important piece of information haha!

Yes, I agree with that.
