### ISSUE TITLE
Why angular-strap

### ISSUE THREAD

**Issue by vinodpahuja** [mgcrea/angular-strap#2239]
Why angular-strap is there when we already have angular-bootstrap?

https://github.com/angular-ui/bootstrap

or there is something more in it?

**Comment by vinodpahuja** [comment]
anybody there?

**Comment by DaleWebb** [comment]
Hello...

**Comment by augustoeliezer** [comment]
angular-strap is **simple**, with **small doc**, and angular-ui is **more complete** with a **too big doc**.

Last commits
angular-strap is on **20 Feb 2017** (by **1** contributor)
angular-ui  **30 Jan 2017** (by **2** contributors)

Anyone know something more?

**Comment by mikejr83** [comment]
We chose to use Angular-Strap because at the time it was written purely in AngularJS. We wanted to minimize the use of JQuery and did not want to bring in all the Bootstrap javascript. Also, I liked how the code was written :)

My organization has chosen this framework over Kendo/Telerik because it is light-weight. 

We (SumTotal Systems) have been working towards 508 compliance. As we repeatedly refine our product to meet the standards that the US gov't imposes it trickles down to the components we use. In this respect we've already have provided contributions for issues that have been alerted to us by The Paciello Group. At the moment we're undergoing a second round of development work towards fixing more 508 issues. I would expect us to have another rounds of commits to submit back to this project before too long. 

That said, we're an enterprise developing enterprise software. We tend to move a little slower than most of the other JavaScript libraries out there. For instance, we're only on AngularJS 1.4.14. We may not even move to 1.5 or 1.6 and instead go to Angular. Also, we have our own UI/UX idiosyncrasies which result in some odd commits. I have tried to make sure that our requirements don't move into this repository because they're probably not the best fit. However, there are some "enhancements" which are available in our repo.
