### ISSUE TITLE
Couldn't type angular brackets inside input box

### ISSUE THREAD

**Issue by hatimn02** [mgcrea/angular-strap#2246]
If i use `bs-options` in input field then i am unable to type angular brackets `< >`

```
<input type="text" class="form-control" bs-options="key for key in ctrl.keySuggestions" 
bs-typeahead ng-model="item.name">
```
Try typing `<hello>`
If you copy paste the text it will work fine but if you try to type then it won't work

http://plnkr.co/edit/9EGvXm07FPiEAeyCn8uf?p=preview

**Comment by DaleWebb** [comment]
I don't believe anyone is actively fixing bugs at the moment.

If you are able to dig into the code and find a solution, we'd be happy to receive a PR on it 👍

**Comment by mkannwischer** [comment]
This is due to 
`var value = selected ? selected.toString().replace(/<(?:.|\n)*?>/gm, '') : '';`
https://github.com/mgcrea/angular-strap/blob/c09125d414186ba0a93c035591d1cfe43310e66b/src/typeahead/typeahead.js#L335
which was introduced in https://github.com/mgcrea/angular-strap/commit/6efd25f3930c292508d43543726fe9c0418e8cda to fix https://github.com/mgcrea/angular-strap/issues/547
