### ISSUE TITLE
Accessibility - bs-select

### ISSUE THREAD

**Issue by sigalvo** [mgcrea/angular-strap#2248]
The select element, and it's dropdown aren't accessible with the keyboard, and the narrator doesn't read the content of the drop-down correctly (it doesn't read the items inside the dropbox).

**Comment by mikejr83** [comment]
@DaleWebb do you mind creating an "Accessibility" label?

@sigalvo Can you give an example of your view and the template you're using in order to get this behavior? Also, could you see if you can reproduce this issue with a [Bootstrap only example](https://getbootstrap.com/docs/3.3/javascript/#dropdowns)? The control structure along with classes directly mimic that so it will be interesting to see if the issue lies with bootstrap.

One of our devs submitted some 508 changes on this control a while ago. We're starting another round of 508 fixes. I have yet to encounter any issues brought up by our contractor regarding `bs-select`. That doesn't mean they don't exist yet, I just haven't gotten that far in our Jira!
