### ISSUE TITLE
[PROJECT] Looking for maintainers

### ISSUE THREAD

**Issue by mgcrea** [mgcrea/angular-strap#2256]
We're currently looking for aspiring maintainers to tackle issues and pull requests!

I have not worked on any Angular.js v1 codebase for more than a year now. For me it's time to move on!

If you have an ongoing project depending on AngularStrap, and would like to become a contributor, it's time to chime in!

**Comment by madflow** [comment]
I am confused by the use of the word "Maintainer" here. Usually the maintainer creates releases and owns and stears the project.

What exactly is meant by ``` aspiring maintainers to tackle issues and pull requests!``` ?  Are you looking for people who can code review, merge PR's and close Issues ("Collaborateurs" in Github lingua, like @DaleWebb )?

Or do you want to give up the maintainership of the project (Creating releases etc.)?

**Comment by richardm** [comment]
I've been using this for a couple of years now. Would be open to hearing more about what's needed. IMO, the biggest need is for a version that works well with Angular.

**Comment by mgcrea** [comment]
@madflow I'm looking for both, wouldn't mind giving releasing rights as well as long as there is a solid "collaboration" history.

**Comment by mikejr83** [comment]
We here SumTotal use this code in our various products. It's obviously important to us. We've worked with many other libraries in the past (Telerik). As a member of the community I think we've done a good job at submitting PRs for those items we feel benefit the community (our 508 work). If some help/sponsorship is required I don't think we would mind providing some. 

Our software is picked up by gov't contractors so we have to hit a lot of accessibility marks. This means a lot of our edits to the code tend to be on the accessibility side. We've actually contracted with [The Paciello Group](https://www.paciellogroup.com/) to review most of our UI stuff. 

Typically edits that are for functionality are defined by our UI/UX teams. These have mostly been confined to our repository. I believe that most of those edits don't benefit the project as a whole since I, and most of my team, think they are of questionable value! :) 

There are some caveats to us participating as a maintainer. Since we're an enterprise developing enterprise software it does take us a bit of time to work on the most current version of things. I just caught a lot of flack for moving from 1.4.9 to 1.4.14 of AngularJS, for instance. As such it means we probably won't be able to provide support for AngularJS 1.5 and 1.6 branches. From the perspective of our changes for 508 compliance, I don't see why we wouldn't be able to move those changes forward. Of course we'll continue to provide them as we get feedback. In regards to providing direction for the project, its features, etc., since we do have a vested stake in seeing this project succeed it would only be natural for us to help provide any guidance we can. Again, we're not moving at the same rapid pace that it seems most projects are doing, but our philosophy is to not let our tech stack stagnate. As we move forward we would like to know that our needs are continually met with a project we're already accustomed to working in.

Hopefully @mgcrea you're not completely divesting yourself of the project. You've created a great suite of controls. Having it written in AngularJS for AngularJS is wonderful. I hope you will be continuing on with the project in the latest version of Angular!

**Comment by keithmullins** [comment]
We use AngularStrap a lot at my company so I would definitely be willing to contribute to maintaining this project and making sure it continues to work well with Angular 1.x

**Comment by powellmichael** [comment]
I would be interested in help maintain this.

**Comment by ur5us** [comment]
“Stale” bots sometimes are the worst. Sad that this died off despite multiple people being willing to step in and contribute. I’m sure this would have helped a few developers.
