### ISSUE TITLE
Popovers cause page to scroll to top on use.

### ISSUE THREAD

**Issue by JoshuaJWilborn** [mgcrea/angular-strap#372]

**Comment by idanen** [comment]
@CodeX278 were you able to reproduce on demo pages?

I'm on version 2.0.3 (our company can't pull the newest at the moment) and the same issue still occurs even after removing the `tabindex="-1"` from the template.

Your solution is the only one that worked for me, however, when I try to use the demo's sample, setting keyboard to `true` doesn't reproduce the issue, so I'm thinking maybe it's fixed in some other way in current version?
