### ISSUE TITLE
template caching bug

### ISSUE THREAD

**Issue by tylercollier** [mgcrea/angular-strap#455]
I'm not sure if this is a bug with angular-strap. It might be an angularjs bug.

Here's my original question: http://stackoverflow.com/questions/21655633/angular-strap-tooltip-not-working-in-ng-repeat/21656097?noredirect=1#21656097. It mentions this plunker demo: http://plnkr.co/edit/ZRk2q2Xn6hObUFJ5SIkr?p=preview.

As @calebboyd discovered and answered on stackoverflow, the issue is with template caching.

At https://github.com/mgcrea/angular-strap/blob/v2.0.0-rc.2/src/tooltip/tooltip.js#L80-81, the `$templateCache` is returning with an _array_ of the previous `$http.get()` call. That's odd; it should be an _object_ with a `.data` property. Thus the subsequent code fails without a legit template.

I'm using angular 1.2.2 right now, but the problem _also_ exists with 1.2.12 (as shown by my plunker link). I'm guessing this is an angular bug? Can you confirm?

@calebboyd created a quick solution by replacing those two lines with the following code (or see this plunker: http://plnkr.co/edit/C2L0Pyt1eTW7lM2Tt7Yf?p=info)

```
return $q.when($templateCache.get(options.contentTemplate) && $templateCache.get(options.contentTemplate)[1] || $http.get(options.contentTemplate, { cache: $templateCache })
              .then(function(response){return response.data}))
              .then(function (contentTemplate) {
```

I fixed it for myself by not using $templateCache but just using

```
$http.get(options.contentTemplate, { cache: true })
```

instead of

```
$http.get(options.contentTemplate, { cache: $templateCache })
```

**Comment by Karankang007** [comment]
Workaround:

Add a random hash version string to your content template url, until this issue is resolved.

```
contentTemplate: 'myCoolSite/myCoolTemplate.html' + '#' + (new Date).getTime()
```

**Comment by hypercuba** [comment]
Hi, i encountered that bug again. Raised 404 on trying to receive template from cache. Fixed in local library by changing "fetchTemplate" method from early version:

`function fetchTemplate(template) {
            if (fetchPromises[template]) return fetchPromises[template];
            return (fetchPromises[template] = $q.when($templateCache.get(template) || $http.get(template))
            .then(function (res) {
                if (angular.isObject(res)) {
                    $templateCache.put(template, res.data);
                    return res.data;
                }
                return res;
            }));
        }`

Could you please help me, whether it may entail some or backfire, or perhaps there is some other way to solve this problem?

**Comment by TiboQc** [comment]
Hi,

Having the same issue when trying to migrate from 2.2.1 to 2.3.6 (better late than never!).

We have an interceptor that adds a timestamp at the end of each `.tpl.html` request to be sent, to disable caching.
The issue is that the new `fetchTemplate` function will always make a `$http.get` call (using cache, mind me), which will pass through the interceptor BEFORE reading the cache.

Our interceptor modifying the URL, the `$templateCache` does not contain the exacte URL anymore and we end up with a 404, as it then tries to read it from the server which doesn't have it as it's only defined in the angular-strap templates.

Temp workaround is the same as @hypercuba (revert to the old `fetchTemplate` method).
