### ISSUE TITLE
angular-strap not working until I import libraries.min.css

### ISSUE THREAD

**Issue by Maidomax** [mgcrea/angular-strap#489]
I had a problem with angular-strap selected boxes not being animated, and very buggy in Firefox. I took a look at the Plunker that is related to the select boxes in the documentation and started commenting out the styleheets. I got the same error in the Plunker when i removed `http://mgcrea.github.io/angular-strap/static/styles/libraries.min.css` from the Plunker. I added this css file to my app, and now everything works. I don't see it in the documentation or on the github repo.
What is this file? Where can I get it? Why isn't it mentioned in the angular-strap documentation?

**Comment by lnu** [comment]
Same here. No animations without libraries.min.css .

**Comment by vmlf01** [comment]
In the "Aside" sample plunker it gives a 404 error getting angular-motion and bootstrap-additions CSS, so that seems to be causing this problem. 
I don't know where libraries.min.css comes from or what is its purpose, maybe @mgcrea can give more details?

Anyway, I think the docs samples need to fix the urls. I'll take a closer look later to create a PR.
