### ISSUE TITLE
Affix and Scrollspy issue 

### ISSUE THREAD

**Issue by elnazabo** [mgcrea/angular-strap#573]
Hi, 
First of all thank for the great job you are doing here. I've found it very helpful indeed.
I've encountered a problem with affix and scrollspy, I've made a working example in Plunker(found bellow), but when I moved it to my Angularjs project it does not work as expected. There are two issues:

1- the bootstrap css additions and removals which are in charge of the positioning in the affix sidebar simply do not happen. And I have no clue why. I don't see what is different from the working Plunker example!

2- In Angularjs the anchor links like  `<a href="#modals">Modal</a>` do not work when you have $routeProvider for configuring your routing. 
I've fixed this by replacing the anchor links with a controller, as follows:

controller:

```
 $scope.scrolltoHref = function (id){
            // set the location.hash to the id of
            // the element you wish to scroll to.
            $location.hash(id);
            // call $anchorScroll()
            $anchorScroll();
        };
```

HTML:

```
 <a href="" ng-click="scrolltoHref('modals')">Modal</a> 
```

Here is the Plunker example which works correctly:
http://plnkr.co/edit/R9ccDkQt92BxNRIODzyh

I appreciate any help or suggestion on these issues, specially the first one which has remained unresolved. And there might be better solutions for the second one as well.

**Comment by iyel** [comment]
Was something implemented to support this use-case?

**Comment by mattsmall** [comment]
I found that using the $anchorScroll service worked to make the links clickable, however doing so caused the scrollspy highlighting of the nav items not to work. Seems as if scrollspy requires having the <a href="#idofbodyelement"> tag corresponding to the main body element in order to work.

I worked around this by adding two <a> elements for each nav item. The first one is hidden via a style which sets padding to 0, but has the href=#id attribute. The second <a> tag has the ng-click="scrollToHref(...). Once in place the scroll spy highlighting showed up, and the nav links were clickable.

<li ng-repeat="stage in stages" bs-scrollspy data-target="#stage_{{stage.id}}">
	<a class="hidden-href" href="#stage_{{stage.id}}"></a>
	<a ng-click="scrollTo('stage_'+ stage.id)">{{stage.name}} </a>
</li>
