### ISSUE TITLE
bs-dropdown and trigger hover

### ISSUE THREAD

**Issue by ProdigyView** [mgcrea/angular-strap#638]
When combining bs-dropdown with data-trigger="click | hover", no menu items can be selected because the menu disappears when you mouseover an option.

**Comment by afc163** [comment]
Don't use button as trigger.

**Comment by thiagog3** [comment]
No solution yet?

**Comment by yilinglu** [comment]
Remove the animation helps get rid of the tooltip/popover/dropdown display show in the wrong location problem. (with animation, the tooltip/popover/dropdown can show up in untended places on the page instead of in the specified locations. For instance, with trigger set to hover, default am-fade on for display, if the mouse cursor enters and leaves the button quickly before the tooltip/popover/dropdown shows up, and then re-enter the button, the tooltip/popover/dropdown will show up elsewhere on the screen, in my observation, often to one of the corners on the screen)

**Comment by hybrisCole** [comment]
``<ul class="dropdown-menu" role="menu" style="margin-top: -10px">```
that negative margin-top will cover the gap
