### ISSUE TITLE
Typeahead: delay ajax requests

### ISSUE THREAD

**Issue by zhenghao1** [mgcrea/angular-strap#749]
Hi,

This is more of a question than an issue as this project doesn't seem to have an IRC chat room.  

I currently set a min-length of 1.  However after that, if I were to type 5 more letters, it fires 5 ajax requests. I only want it to fire the ajax requests after a specified 1-2 seconds.  Is such a feature possible?  I know there's a delay feature, but the docs aren't really clear.

`If a number is supplied, delay is applied to both hide/show`

Is this a UI thing or is it really delaying the ajax requests?

**Comment by mzgajner** [comment]
I have the same issue, but I suppose this is the same case as with the delay - the setting only affects visual elements, it doesn't affect async calls in the background.

**Comment by smurugavel** [comment]
yes same issue here.
+1 to fix the problem

**Comment by axschech** [comment]
@mgcrea was there ever a PR for this? Yes you can use ngModelOptions on a per typeahead instance basis, but a global debounce for all typeaheads (via typeaheadProvider) would be really nice too!

**Comment by khashayar** [comment]
ngModelOptions doesn't serve the purpose, let's say I set the `debounce` in ngModelOptions to 300 ms, and I type 'test'... then 350 ms pause and 'ing'... what happens is two requests would be sent to server, first with 'test' and second with 'testing'. Now let's say the server responds the first request with some delay so that the result of 2nd query comes first and 1st query comes last... what will be shown in the autocomplete result is a set, matched with 'test' query which is wrong. Makes sense?

**Comment by axschech** [comment]
@khashayar I was referencing this: https://github.com/mgcrea/angular-strap/pull/696

**Comment by joaoborsoi** [comment]
It would be nice to have this documented.
