### ISSUE TITLE
Do not place multiple alerts on top of each other

### ISSUE THREAD

**Issue by amergin** [mgcrea/angular-strap#890]
It would be helpful if multiple alerts were not stacked on top of each other, but instead placed in a row like [angular-growl](https://github.com/marcorinck/angular-growl) implements it ([example picture](https://github.com/marcorinck/angular-growl/blob/master/doc/screenshot.jpg)).

**Comment by cnelissen** [comment]
+1 for using nth-child, easy and elegant.

**Comment by jpdavy** [comment]
Instead of nth-child, I used nth-of-type(n)
`body > div.alert.top-right:nth-of-type(2) {
  top: 15px;
}
body > div.alert.top-right:nth-of-type(3) {
  top: 80px;
}
body > div.alert.top-right:nth-of-type(4) {
  top: 145px;
}
body > div.alert.top-right:nth-of-type(5) {
  top: 210px;
}
body > div.alert.top-right:nth-of-type(6) {
  top: 275px;
}`
