### ISSUE TITLE
Scrollspy doesn't work when target content changes height

### ISSUE THREAD

**Issue by rockyromano** [mgcrea/angular-strap#911]
I have a set of divs (which are targeted by a sidenav) which have content within that is shown/hidden based on a user's progress through a form. Once they shift in size it seems only the original, initialized offsets, are referenced. A refresh option would be great

**Comment by mfields106** [comment]
Same issue here

**Comment by jhachey** [comment]
+1 for this issue

**Comment by zsheffer** [comment]
Any update on this one?

**Comment by jacquesdancona** [comment]
+1
A list of larger ng-repeated elements will completely mess up the scrollspy.

**Comment by polo2ro** [comment]
On my page with lazy-loading on scroll, i successfully fixed my scollSpy using the service:
```javascript
var scrollspy = $scrollspy(angular.element(document.getElementsByClassName('bs-sidenav')[0]), {});
scrollspy.init();
```
This will probably not fix the problem when target content changes height but this work well when new items are added to the menu.

**Comment by aske-cph** [comment]
Any news on this?

My problem is using ui-router. I hav a nav outside a ui-view window. The nav contains a list of users, and the view contains div's for each user. The view can be changed though, to show different user content so the height naturally changes, but the offsets are now wrong.

Also Scrollspy doesn't work on first load because the view has not been loaded yet. 

So +1 for a refresh function for when the dom has changed. That would also solve the ui-router problem (that scrollspy inits before the view has loaded).
