### ISSUE TITLE
bs-radio-group doesn't work with Bootstrap

### ISSUE THREAD

**Issue by k-funk** [mgcrea/angular-strap#999]
The radio group clicks don't effect the model when bootstrap is included. Try commenting out the jquery/bootstrap script tags, and you'll see.

See plunkr:
http://plnkr.co/edit/xUWF3svQ03MsNtJgDklQ?p=preview

**Comment by statpro-awebb** [comment]
I also need Bootstrap's JavaScript to run alongside AngularStrap - mainly because of edge-case issues I found with modals done the AngularStrap way.  Using plain-vanilla Bootstrap works better, according to my mileage at any rate.

The root cause of this issue (regarding `bs-radio-group` not hooking up to the model) is because AngularStrap compiles its directive with the following:-

    element.attr('data-toggle', 'buttons');

I.e. it adds attribute `data-toggle="buttons"` to the surrounding div.  It doesn't do this because it *wants* Bootstrap's JavaScript to kick in (an unfortunate side-effect), but in order to get 3 lines of styling that remove the circle from the radio inputs, and make them look like more normal buttons:-

    position: absolute;
    clip: rect(0, 0, 0, 0);
    pointer-events: none;

I wonder if AngularStrap could get this styling some other way, and omit the need for the `bs-radio-group` directive (and other, similar directives) to add the `data-toggle` attribute?  This could go a long way to making AngularStrap and Boostrap's Js peacefully co-exist (hopefully).
